### ISSUE TITLE
Block-scoped declarations in lib/htmlbars-plugin.js

### ISSUE THREAD

**Issue by azhiv** [nikityy/ember-cli-bem#11]
After installing `ember-cli-bem` plugin I get the following error during build:
`Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

which is caused by the file in the subject. Could you please add 'use strict'; to the top of the file? I know this error will be gone once I upgrade node but right now in our corporate development environment we are using v4.8.0 and it's not gonna change in the nearest future.

Looks like a minor change...

**Comment by nikityy** [comment]
Seems to be fixed in #12, therefore closing this issue.
