### ISSUE TITLE
Missing module ember-get-config

### ISSUE THREAD

**Issue by kennstenicht** [nikityy/ember-cli-bem#9]
After updating to v1.0.0-beta.1 i get the following error:  
`Error: Could not find module 'ember-get-config' imported from 'ember-cli-bem/mixins/bem'`

**Comment by nikityy** [comment]
@kennstenicht seems like I marked 'ember-get-config' as a devDependency, so it doesn't install on production builds. I've made #10, please check if it works with it.

**Comment by nikityy** [comment]
@kennstenicht I suppose that thumbs up means that everything is fine. The patch is included in '1.0.0-beta.2' release.
